version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
      - node_modules:/opt/app/node_modules

volumes:
  node_modules:
