ARG VERSION=16.14.2

FROM node:$VERSION AS build

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

ENV APP /opt/app

WORKDIR $APP

COPY package.json pnpm-lock.yaml .
RUN pnpm install

COPY docker-entrypoint-dev.sh /
RUN chmod +x /docker-entrypoint-dev.sh
COPY . .

ENTRYPOINT ["/docker-entrypoint-dev.sh"]
CMD ["dev"]
